FROM bitnami/kafka:latest

EXPOSE 9092 2181

ENV KAFKA_CFG_ZOOKEEPER_CONNECT=localhost:2181
ENV ALLOW_PLAINTEXT_LISTENER=yes
ENV KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
ENV KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://render-kafka-docker-image.onrender.com