FROM bitnami/kafka:latest

EXPOSE 9092 9093 #Expose both kafka and kraft ports.

#KRaft mode configuration.
ENV KAFKA_CFG_NODE_ID=0
ENV KAFKA_CFG_PROCESS_ROLES=controller,broker
ENV KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
#Listeners
ENV KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
ENV KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://your-render-kafka-service.onrender.com:9092
ENV KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
ENV KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
ENV KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT