services:
  - type: web
    name: kafka
    dockerfilePath: Dockerfile
    port: 9092
    envVars:
      - key: KAFKA_CFG_NODE_ID
        value: "0"
      - key: KAFKA_CFG_PROCESS_ROLES
        value: "controller,broker"
      - key: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
        value: "0@kafka:9093"
      - key: KAFKA_CFG_LISTENERS
        value: "PLAINTEXT://:9092,CONTROLLER://:9093"
      - key: KAFKA_CFG_ADVERTISED_LISTENERS
        value: "PLAINTEXT://your-render-kafka-service.onrender.com:9092"
      - key: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
        value: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
      - key: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
        value: "CONTROLLER"
      - key: KAFKA_CFG_INTER_BROKER_LISTENER_NAME
        value: "PLAINTEXT"